[metadata]
name = beamit
version = 0.1.0
author = Sai Kubair Kota
description = Computational modeling of fracture in geometrically exact beams based on the DG/CZM approach
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT

[options]
package_dir =
    = lib
packages = find:
python_requires = >=3.10
install_requires =
    scipy==1.15.3
    numpy==2.2.6
    numpy-quaternion==2024.0.8
    pyevtk==1.6.0
    pytest==8.3.5
    pyvista==0.45.0
    matplotlib==3.10.0

[options.packages.find]
where = lib
